#!/usr/bin/env python3
"""Subset the Phosphor icon fonts down to the glyphs this site actually uses.

The upstream package ships ~6 MB per weight and the site loaded it from unpkg as a
blocking script. This emits a local woff2 + CSS containing only the referenced
glyphs. Re-run after adding or removing any ph-* icon:

    pip install fonttools brotli
    python3 scripts/subset-icons.py
"""
import os, re, sys, glob

SRC = "node_modules/@phosphor-icons/web/src"
OUT_FONT = "public/fonts"
OUT_CSS = "app/phosphor.css"
# class prefix -> (package dir, font family, font file stem)
WEIGHTS = {
    "ph":      ("regular", "Phosphor",      "Phosphor"),
    "ph-bold": ("bold",    "Phosphor-Bold", "Phosphor-Bold"),
    "ph-fill": ("fill",    "Phosphor-Fill", "Phosphor-Fill"),
}

def used_icons():
    """Map weight-class -> set of icon names, by scanning className strings."""
    found = {w: set() for w in WEIGHTS}
    for path in glob.glob("app/**/*.js", recursive=True):
        for cls in re.findall(r'className="([^"]*)"', open(path, encoding="utf-8").read()):
            tokens = cls.split()
            if not any(t in WEIGHTS for t in tokens):
                continue
            # the weight is the most specific prefix present; bare "ph" is regular
            weight = next((t for t in tokens if t in WEIGHTS and t != "ph"), "ph")
            for t in tokens:
                if t.startswith("ph-") and t not in WEIGHTS:
                    found[weight].add(t)
    return found

def codepoints(weight_dir, prefix, names):
    """Pull each icon's codepoint out of the shipped stylesheet."""
    css = open(f"{SRC}/{weight_dir}/style.css", encoding="utf-8").read()
    out = {}
    for name in sorted(names):
        m = re.search(r'\.%s\.%s:before\s*\{\s*content:\s*"\\([0-9a-fA-F]+)"' %
                      (re.escape(prefix), re.escape(name)), css)
        if not m:
            print(f"  !! no codepoint for {prefix}.{name}", file=sys.stderr)
            continue
        out[name] = int(m.group(1), 16)
    return out

def main():
    from fontTools import subset

    os.makedirs(OUT_FONT, exist_ok=True)
    used = used_icons()
    css_parts, total = [], 0

    for prefix, (wdir, family, stem) in WEIGHTS.items():
        names = used[prefix]
        if not names:
            continue
        cps = codepoints(wdir, prefix, names)
        if not cps:
            continue

        src = f"{SRC}/{wdir}/{stem}.ttf"
        dst = f"{OUT_FONT}/{stem.lower()}-subset.woff2"
        opts = subset.Options()
        opts.flavor = "woff2"
        opts.desubroutinize = True
        opts.layout_features = []          # no ligatures needed; we use :before content
        opts.notdef_outline = True
        font = subset.load_font(src, opts)
        s = subset.Subsetter(options=opts)
        s.populate(unicodes=list(cps.values()))
        s.subset(font)
        subset.save_font(font, dst, opts)
        font.close()

        size = os.path.getsize(dst)
        total += size
        print(f"{prefix:8} {len(cps):2} glyphs -> {dst}  {size/1024:.1f} KB")

        css_parts.append(f"""@font-face {{
  font-family: "{family}";
  src: url("/fonts/{os.path.basename(dst)}") format("woff2");
  font-weight: normal;
  font-style: normal;
  font-display: block;
}}

.{prefix} {{
  font-family: "{family}" !important;
  speak: never;
  font-style: normal;
  font-weight: normal;
  font-variant: normal;
  text-transform: none;
  line-height: 1;
  letter-spacing: 0;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  display: inline-block;
}}
""")
        for name, cp in sorted(cps.items()):
            css_parts.append(f'.{prefix}.{name}:before {{ content: "\\{cp:x}"; }}')
        css_parts.append("")

    header = ("/* Generated by scripts/subset-icons.py -- do not edit by hand.\n"
              "   Re-run that script after adding or removing any ph-* icon. */\n\n")
    open(OUT_CSS, "w", encoding="utf-8").write(header + "\n".join(css_parts))
    print(f"\ntotal woff2 {total/1024:.1f} KB, css {os.path.getsize(OUT_CSS)/1024:.1f} KB -> {OUT_CSS}")

if __name__ == "__main__":
    main()
